Config = {}
Config.DrawDistance               = 100.0
Config.MarkerType                 = 27
Config.MarkerSize                 = { x = 1.5, y = 1.5, z = 0.5 }
Config.MarkerColor                = { r = 50, g = 50, b = 204 }

Config.Locations = {
    Police = {
        label = 'Police',
        Marker = {
            vector3(439.60, -981.20, 30.00)
        },
        Spawns = {
            -- Front
            vector4(408.76, -980.10, 29.26, 50), -- right most
            vector4(408.05, -984.25, 29.26, 50),
            vector4(407.78, -988.63, 29.26, 50),
            vector4(407.86, -992.87, 29.26, 50),
            vector4(408.08, -998.04, 29.26, 50), -- left most
            -- Side
            vector4(427.258, -1027.455, 28.99, 4), -- close
            vector4(430.749, -1027.023, 28.92, 4),
            vector4(434.675, -1026.88, 28.85, 4),
            vector4(438.669, -1026.705, 28.78, 4),
            vector4(441.712, -1025.447, 28.72, 4),
            vector4(445.608, -1025.116, 28.65, 4), -- far
        },
        Uniform = {
            male = {
                ['tshirt_1'] = 58,  ['tshirt_2'] = 0,
                ['torso_1'] = 55,   ['torso_2'] = 0,
                ['decals_1'] = 8,   ['decals_2'] = 2,
                ['arms'] = 41,
                ['pants_1'] = 25,   ['pants_2'] = 0,
                ['shoes_1'] = 25,   ['shoes_2'] = 0,
                ['helmet_1'] = -1,  ['helmet_2'] = 0,
                ['chain_1'] = 0,    ['chain_2'] = 0,
                ['ears_1'] = 2,     ['ears_2'] = 0
            },
            female = {
                ['tshirt_1'] = 35,  ['tshirt_2'] = 0,
                ['torso_1'] = 48,   ['torso_2'] = 0,
                ['decals_1'] = 7,   ['decals_2'] = 2,
                ['arms'] = 44,
                ['pants_1'] = 34,   ['pants_2'] = 0,
                ['shoes_1'] = 27,   ['shoes_2'] = 0,
                ['helmet_1'] = -1,  ['helmet_2'] = 0,
                ['chain_1'] = 0,    ['chain_2'] = 0,
                ['ears_1'] = 2,     ['ears_2'] = 0
            }
        },
        model = {
            'police',
            'police2',
            'police3',
            'police4',
            'fbi',
            'fbi2',
            'pranger',
            'sheriff',
            'sheriff2'
        }
    },
    Robber = {
        label = 'Robber',
        Marker = {
            vector3(442.65, -981.36, 30.00)
        },
        Spawns = {
            vector4(390.45, -987.61, 29.42, 355)
        },
        Uniform = {
            male = {
                ['tshirt_1'] = 10,  ['tshirt_2'] = 0,
                ['torso_1'] = 86,   ['torso_2'] = 4,
                ['decals_1'] = 0,   ['decals_2'] = 0,
                ['arms'] = 0,
                ['pants_1'] = 55,   ['pants_2'] = 0,
                ['shoes_1'] = 25,   ['shoes_2'] = 0,
                ['helmet_1'] = -1,  ['helmet_2'] = 0,
                ['chain_1'] = 0,    ['chain_2'] = 0,
                ['ears_1'] = 0,     ['ears_2'] = 0
            },
            female = {
                ['tshirt_1'] = 10,  ['tshirt_2'] = 0,
                ['torso_1'] = 86,   ['torso_2'] = 4,
                ['decals_1'] = 0,   ['decals_2'] = 0,
                ['arms'] = 0,
                ['pants_1'] = 55,   ['pants_2'] = 0,
                ['shoes_1'] = 25,   ['shoes_2'] = 0,
                ['helmet_1'] = -1,  ['helmet_2'] = 0,
                ['chain_1'] = 0,    ['chain_2'] = 0,
                ['ears_1'] = 0,     ['ears_2'] = 0
            }
        },
        model = {
            'kuruma',
            'Blista',
            'Blista2',
            'Blista3',
            'Brioso',
            'Dilettante',
            'Dilettante2',
            'Issi2',
            'Panto',
            'Prairie',
            'Rhapsody',
            'CogCabrio',
            'Exemplar',
            'F620',
            'Felon',
            'Felon2',
            'Jackal',
            'Oracle',
            'Oracle2',
            'Sentinel',
            'Sentinel2',
            'Windsor',
            'Windsor2',
            'Zion',
            'Zion2',
            'Blade',
            'Buccaneer',
            'Buccaneer2',
            'Chino',
            'Chino2',
            'Dominator',
            'Dominator2',
            'Dukes',
            'Dukes2',
            'Faction',
            'Faction2',
            'Faction3',
            'Gauntlet',
            'Gauntlet2',
            'Hotknife',
            'Lurcher',
            'Moonbeam',
            'Moonbeam2',
            'Nightshade',
            'Phoenix',
            'Picador',
            'RatLoader',
            'RatLoader2',
            'Ruiner',
            'Ruiner2',
            'SabreGT',
            'SabreGT2',
            'Sadler2',
            'SlamVan',
            'SlamVan2',
            'SlamVan3',
            'Stalion',
            'Stalion2',
            'Tampa',
            'Tampa3',
            'Vigero',
            'Virgo',
            'Virgo2',
            'Virgo3',
            'Voodoo',
            'Voodoo2',
            'BfInjection',
            'Bifta',
            'Blazer',
            'Blazer2',
            'Blazer3',
            'Blazer5',
            'Bodhi2',
            'Brawler',
            'DLoader',
            'Dune',
            'Dune2',
            'Dune3',
            'Dune4',
            'Dune5',
            'Insurgent',
            'Insurgent2',
            'Insurgent3',
            'Kalahari',
            'Lguard',
            'Marshall',
            'Mesa',
            'Mesa2',
            'Mesa3',
            'Monster',
            'Nightshark',
            'RancherXL',
            'RancherXL2',
            'Rebel',
            'Rebel2',
            'Sandking',
            'Sandking2',
            'Technical',
            'Technical2',
            'Technical3',
            'TrophyTruck',
            'TrophyTruck2',
            'BJXL',
            'Baller',
            'Baller2',
            'Baller3',
            'Baller4',
            'Baller5',
            'Baller6',
            'Cavalcade',
            'Cavalcade2',
            'Contender',
            'Dubsta',
            'Dubsta2',
            'Dubsta3',
            'FQ2',
            'Granger',
            'Gresley',
            'Habanero',
            'Huntley',
            'Landstalker',
            'Patriot',
            'Radi',
            'Rocoto',
            'Seminole',
            'Serrano',
            'XLS',
            'XLS2',
            'Asea',
            'Asea2',
            'Asterope',
            'Cog55',
            'Cog552',
            'Cognoscenti',
            'Cognoscenti2',
            'Emperor',
            'Emperor2',
            'Emperor3',
            'Fugitive',
            'Glendale',
            'Ingot',
            'Intruder',
            'Limo2',
            'Premier',
            'Primo',
            'Primo2',
            'Regina',
            'Romero',
            'Stanier',
            'Stratum',
            'Stretch',
            'Surge',
            'Tailgater',
            'Warrener',
            'Washington',
            'Alpha',
            'Banshee',
            'Banshee2',
            'BestiaGTS',
            'Buffalo',
            'Buffalo2',
            'Buffalo3',
            'Carbonizzare',
            'Comet2',
            'Comet3',
            'Coquette',
            'Elegy',
            'Elegy2',
            'Feltzer2',
            'Feltzer3',
            'Furoregt',
            'Fusilade',
            'Futo',
            'Infernus2',
            'Jester',
            'Jester2',
            'Khamelion',
            'Kuruma',
            'Kuruma2',
            'Lynx',
            'Massacro',
            'Massacro2',
            'Ninef',
            'Ninef2',
            'Omnis',
            'Penumbra',
            'RapidGT',
            'RapidGT2',
            'Raptor',
            'Ruston',
            'Schafter2',
            'Schafter3',
            'Schafter4',
            'Schafter5',
            'Schafter6',
            'Schwarzer',
            'Seven70',
            'Specter',
            'Specter2',
            'Sultan',
            'Surano',
            'Tampa2',
            'Tropos',
            'Verlierer2',
            'Ardent',
            'BType',
            'BType2',
            'BType3',
            'Casco',
            'Cheetah2',
            'Coquette2',
            'Coquette3',
            'JB700',
            'Mamba',
            'Manana',
            'Monroe',
            'Peyote',
            'Pigalle',
            'Stinger',
            'StingerGT',
            'Torero',
            'Tornado',
            'Tornado2',
            'Tornado3',
            'Tornado4',
            'Tornado5',
            'Tornado6',
            'ZType',
            'Adder',
            'Bullet',
            'Cheetah',
            'EntityXF',
            'FMJ',
            'GP1',
            'Infernus',
            'RE7B',
            'Nero',
            'Nero2',
            'Osiris',
            'Penetrator',
            'Pfister811',
            'Prototipo',
            'Reaper',
            'Sheava',
            'SultanRS',
            'Superd',
            'T20',
            'Tempesta',
            'Turismo2',
            'Turismor',
            'Tyrus',
            'Vacca',
            'Vagner',
            'Voltic',
            'Voltic2',
            'Zentorno',
            'Italigtb',
            'Italigtb2',
            'XA21',
            'Bison',
            'Bison2',
            'Bison3',
            'BobcatXL',
            'Boxville',
            'Boxville2',
            'Boxville3',
            'Boxville4',
            'Boxville5',
            'Burrito',
            'Burrito2',
            'Burrito3',
            'Burrito4',
            'Burrito5',
            'Camper',
            'GBurrito',
            'GBurrito2',
            'Journey',
            'Minivan',
            'Minivan2',
            'Paradise',
            'Pony',
            'Pony2',
            'Rumpo',
            'Rumpo2',
            'Rumpo3',
            'Speedo',
            'Speedo2',
            'Surfer',
            'Surfer2',
            'Taco',
            'Youga',
            'Youga2'
        }
    }
}